bot/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "bot"

urlpatterns = [
    path('', csrf_exempt(views.index), name='index'),
    path('send_message', views.send_message, name='send_message'),

]

tsn/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from main.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('bot/', include('bot.urls')),

]

handler404 = pageNotFound

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    # path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('lk/', views.lk_user, name='lk_user'),
    path('receipt/', views.receipt, name='receipt'),
    path('show_zayavka/<int:id>/', views.show_zayavka, name='show_zayavka'),
    path('delete_zayavka/<int:pk>/', views.deletezayavka, name='delete_zayavka'),
    # path('add_users/', views.add_user, name='add_users'),
    # path('add_pokazaniya/', views.add_pokazaniya, name='add_pokazaniya'),
    path('edit_phone_ajax/', views.EditPhoneAjax.as_view(), name='edit_phone_ajax'),
    path('edit_email_ajax/', views.EditEmailAjax.as_view(), name='edit_email_ajax'),
    path('edit_rec_doc_ajax/', views.EditRecDocAjax.as_view(), name='edit_rec_doc_ajax'),
    path('password_change_ajax/', views.ChangePasswordAjax.as_view(), name='password_change_ajax'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('pokazaniya_write_ajax/', views.PokazaniyaWriteAjax.as_view(), name='pokazaniya_write_ajax'),
    path('zayavka_write_ajax/', views.ZayavkaWriteAjax.as_view(), name='zayavka_write_ajax'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """
    Абстрактная модель user
    """
    fio = models.CharField(max_length=200, verbose_name='ФИО', blank=True)
    kv = models.IntegerField(verbose_name='Квартира', blank=True, default=0)
    ls = models.IntegerField(verbose_name='Лицевой счет', blank=True, default=0)
    address = models.CharField(max_length=250, verbose_name='Адрес', blank=True)
    sq = models.CharField(max_length=10, verbose_name='Площадь', blank=True)
    phone = models.CharField(max_length=17, verbose_name='Телефон', blank=True)
    TYPE_SELECT = (
        (False, 'Бумажный'),
        (True, 'E-mail'),
    )
    rec_doc = models.BooleanField(default=False, choices=TYPE_SELECT, verbose_name="Способ получения платежных "
                                                                                   "документов", blank=True)
    check_email = models.BooleanField(default=False, verbose_name='Проверка email', blank=True)

    class Meta:
        verbose_name = 'Пользователи'
        verbose_name_plural = 'Пользователи'
        ordering = ['kv']


######################################################################
class Receipts(models.Model):
    """
    Модель для хранения квитанций за квартиру
    """
    ls = models.IntegerField(verbose_name='Лицевой счет', blank=True, default=0)
    date = models.DateField(verbose_name='За какой месяц')
    file = models.FileField(upload_to="receipts/", verbose_name="Квитанция")
    show = models.IntegerField(verbose_name="Кол-во скачиваний", default=0)

    class Meta:
        verbose_name = 'Квитанции'
        verbose_name_plural = 'Квитанции'
        ordering = ['ls']

    def __str__(self):
        return f"Платежка л.сч: {self.ls}"
######################################################################

######################################################################

users/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login, logout
from users.forms import *
from main.forms import PokazaniyaForm, ZayavkaForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import get_user_model
from django.views import View
from django.core.mail import send_mail
from django.conf import settings
from django.http import JsonResponse
import re
from users.utils import check_email, send_email_for_verify
from django.utils.http import urlsafe_base64_decode
from django.contrib.auth.tokens import default_token_generator as token_generator
from django.core.exceptions import ValidationError
from main.models import MeterDev, Pokazaniya, PokazaniyaUser, Zayavki
from django.db import IntegrityError
import datetime
from .models import Receipts

User = get_user_model()


def login_user(request):
    if request.method == "POST":
        form = LoginUserForm(data=request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            user = authenticate(username=username, password=password)
            if user:
                login(request, user)
                return redirect('users:lk_user')
    else:
        form = LoginUserForm()

    context = {
        'title': 'Вход в личный кабинет',
        'form': form,
    }
    return render(request, 'users/login.html', context)


@login_required
def profile(request):
    data_user = get_object_or_404(User, ls=request.user.username)
    form = EditProfile(data=data_user)  # (fio=data_user.fio)
    form_phone = EditPhone(data=data_user)
    form_email = EditEmail(data=data_user)
    form_password = ChangeForm(user=request.user)

    context = {
        'title': 'Профиль пользователя',
        'data_user': data_user,
        'form': form,
        'form_phone': form_phone,
        'form_email': form_email,
        'form_password': form_password
    }
    return render(request, 'users/profile.html', context)


@login_required()  # login_url="/users/login/"
def lk_user(request):
    zayavki = Zayavki.objects.filter(user_id=request.user.id)
    data_user = get_object_or_404(User, ls=request.user.username)
    form_pokaz = PokazaniyaForm(data=data_user)
    form_zayavka = ZayavkaForm(data=data_user)
    form_receipt = Lk_receiptForm()
    device = MeterDev.objects.filter(kv=request.user.kv).all()
    pokaz_dev = list(Pokazaniya.objects.filter(kv=request.user.kv).order_by("-date").values())
    p = []
    if pokaz_dev:
        p = pokaz_dev[0]

    context = {
        'title': "Личный кабинет",  # request.user.username,
        'data_user': data_user,
        'device': device,
        'zayavki': zayavki,
        'pokaz_dev': p,
        'form_pokaz': form_pokaz,
        'form_zayavka': form_zayavka,
        'form_receipt': form_receipt,
    }
    return render(request, 'users/lk.html', context)


###############################################################
def show_zayavka(request, id):
    zayavka = Zayavki.objects.filter(user_id=request.user.id).get(id=id)
    context = {
        'title': "Личный кабинет",  # request.user.username,
        'zayavka': zayavka
    }
    return render(request, 'users/show_zayavka.html', context)


###############################################################
class ChangePasswordAjax(View):
    model = User

    def post(self, request):
        form_password = PasswordChangeForm(user=request.user, data=request.POST)
        if form_password.is_valid():
            form_password.save()
            return JsonResponse(data={'status': 201, 'response': "Успешно, войдите заново!"}, status=200)

        errors = form_password.errors.as_json()
        return JsonResponse(data={'status': 400, 'error': errors}, status=200)


#########################################################
class EditPhoneAjax(View):
    def post(self, request):
        reg = "^[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}$"
        check_num = re.search(reg, request.POST.get('phone'))
        if check_num:
            User.objects.filter(username=request.user.username).update(phone=request.POST.get('phone'))
            return JsonResponse(data={'status': 201, 'response': "Успешно"}, status=200)

        return JsonResponse(data={'status': 400, 'error': "Проверьте правильность номера"}, status=200)


#########################################################
class EditEmailAjax(View):
    def post(self, request):
        if check_email(request.POST.get('email')):
            if request.POST.get('email') == request.user.email and (request.user.check_email == 1):
                return JsonResponse(data={'status': 201, 'response': "Успешно"}, status=200)
            else:
                User.objects.filter(username=request.user.username).update(email=request.POST.get('email'),
                                                                           check_email=0)
                send_email_for_verify(request, request.user, request.POST.get('email'))
                return JsonResponse(data={'status': 201, 'response': "Подтверждение email на почте"}, status=200)

        return JsonResponse(data={'status': 400, 'error': 'Проверьте правильность email'}, status=200)


###############################################################
class EditRecDocAjax(View):
    def post(self, request):
        print(f"rec_doc:{request.POST.get('rec_doc')}")
        if request.POST.get('rec_doc') and request.user.check_email:
            User.objects.filter(username=request.user.username).update(rec_doc=request.POST.get('rec_doc'))
            return JsonResponse(data={'status': 201, 'response': "Успешно"}, status=200)

        return JsonResponse(data={'status': 400, 'error': "Нет или неподтвержден email"}, status=200)


###############################################################
def logout_user(request):
    if request.method == "POST":
        logout(request)
        return redirect('home')


#########################################################
@login_required
def deletezayavka(request, pk):
    zayavka = get_object_or_404(Zayavki, pk=pk, user=request.user)
    if request.method == "POST":
        zayavka.delete()
        return redirect('users:lk_user')


#########################################################
class ZayavkaWriteAjax(View):
    def post(self, request):
        reg = "^[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}$"
        check_num = re.search(reg, request.POST.get('phone'))
        if check_num is None:
            return JsonResponse(data={'status': 400, 'error': "Проверьте правильность номера"}, status=200)
        if len(request.POST.get('description')) < 5:
            return JsonResponse(data={'status': 400, 'error': 'Поле описание менее 5 символов'}, status=200)
        try:
            Zayavki.objects.create(user=request.user, description=request.POST.get('description'),
                                   phone=request.POST.get('phone'))
            # send email admin
            mess = ("Новое сообщение от " + request.user.username + "; Тел: " + request.POST.get('phone') +
                    "; Сообщение: " + request.POST.get('description'))
            send_mail('Уведомление с сайта ТСН', mess, settings.EMAIL_HOST_USER,
                      [settings.EMAIL_FROM_ADMIN, settings.EMAIL_FROM_CLIENT], fail_silently=False, )
        except IntegrityError:
            return JsonResponse(data={'status': 400, 'error': "Ошибка"}, status=200)
        return JsonResponse(data={'status': 201, 'response': "Заявка успешно отправлена"}, status=200)


#########################################################
class EmailVerify(View):
    def get(self, request, uidb64, token):
        user = self.get_user(uidb64)

        if user is not None and token_generator.check_token(user, token):
            user.check_email = True
            user.save()
            # login(request, user)
            return redirect('users:profile')
        return redirect('users:invalid_verify')

    @staticmethod
    def get_user(uidb64):
        try:
            uid = urlsafe_base64_decode(uidb64).decode()
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError,
                User.DoesNotExist, ValidationError):
            user = None
        return user


#########################################################
class PokazaniyaWriteAjax(View):
    def post(self, request):

        now = datetime.datetime.now()
        if PokazaniyaUser.objects.filter(date__month=now.month):
            return JsonResponse(data={'status': 400, 'error': "В этом месяце вы уже передавали показания"}, status=200)
        try:
            PokazaniyaUser.objects.create(
                kv=request.POST.get('kv'),
                hv=request.POST.get('hv'),
                gv=request.POST.get('gv'),
                e=request.POST.get('e')
            )
            return JsonResponse(data={'status': 201, 'response': "Показания добавлены"}, status=200)
        except ValueError:
            return JsonResponse(data={'status': 400, 'error': "Ошибка"}, status=200)

        # return JsonResponse(data={'status': 201, 'response': "Показания добавлены"}, status=200)
        # return JsonResponse(data={'status': 400, 'error': "Ошибка"}, status=200)


#########################################################
def receipt(request):
    try:
        kvitan = Receipts.objects.filter(date__month=request.POST['month'], date__year=request.POST[
            'year']).get(ls=request.user.ls)
    except Receipts.DoesNotExist:
        kvitan = None

    context = {
        'title': "Платежный документ",  # request.user.username,
        'kvitan': kvitan,

    }
    return render(request, 'users/receipt.html', context)
#########################################################

users/templates/users/invalid_verify.html
{% extends 'main/base.html' %}

{% block content %}
<div class="container">
    <div class="row">
        <p>Ваша ссылка не корректна</p>
        
    </div>
</div>
{% endblock %}

users/templates/users/lk.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<!--CONTENT-->
<div class="container">
    <h2>Личный кабинет</h2>
    <p>Лицевой счет: <b>№ {{ user.username }}</b></p>
    <p>Адрес: {{data_user.address}}</p>
    <p>Площадь помещения:&nbsp;<b>{{data_user.sq}}</b>&nbsp;кв.м</p>
    <!-- <hr class="space m" /> -->
    <div class="row">
        <div class="col-md-6 col-sm-12 my-1">
            <div class="container-cont ">
                <div class="title">Передать показания ПУ</div>
                <div class="alert alert-danger d-none error_pokaz" role="alert"></div>
                <div class="alert alert-success d-none ok_pokaz" role="alert"></div>
                <form action="{%url 'users:pokazaniya_write_ajax' %}" id="form_send_pokazaniya" method="post">
                    {% csrf_token %}
                    {{form_pokaz.kv}}
                    <small><u>(показания принимаются с 22 по 24 число)</u></small>
                    <table class="table-sm ">
                        <tr>
                            <td><b>ХВС</b>&nbsp;<img src="{% static 'main/img/meter-blue.svg' %}" height="50"
                                                    width="50"><br>
                                {% if not device %}
                                <small>(Счетчик № ------)<br><u>Дата след.поверки --.--.----</u></small>
                                {% endif %}

                                {%for dev in device %}
                                {% if "hv" in dev.type %}
                                <small>({{dev.name}} № {{dev.number}})<br><u>Дата след.поверки
                                    {{dev.data_pov_next}}</u></small>
                                {% endif %}
                                {% endfor %}
                            </td>

                        </tr>
                        <tr>
                            <td><small>Последние показания <i><u>({{pokaz_dev.date}})</u></i>:
                                <b>{{pokaz_dev.hv}}</b></small></td>
                        </tr>
                        <tr>
                            <td><small><span
                                    style="font-size: 12px;"><i>Вводите показания целым числом</i></span></small><br>
                                {{form_pokaz.hv}}
                            </td>

                        </tr>
                        <tr>
                            <td><b>ГВС</b>&nbsp;<img src="{% static 'main/img/meter-water-hot.svg' %}" height="50"
                                                    width="50"><br>
                                {% if not device %}
                                <small>(Счетчик № ------)<br><u>Дата след.поверки --.--.----</u></small>
                                {% endif %}
                                {%for dev in device %}
                                {% if "gv" in dev.type %}
                                <small>({{dev.name}} № {{dev.number}})<br><u>Дата след.поверки
                                    {{dev.data_pov_next}}</u></small>
                                {% endif %}
                                {% endfor %}

                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><small>Последние показания <i><u>({{pokaz_dev.date}})</u></i>:
                                <b>{{pokaz_dev.gv}}</b></small></td>
                        </tr>
                        <tr>
                            <td><small><span
                                    style="font-size: 12px;"><i>Вводите показания целым числом</i></span></small><br>
                                {{form_pokaz.gv}}
                            </td>

                        </tr>
                        <tr>
                            <td><b>Электроэнергия</b>&nbsp;<img src="{% static 'main/img/electric-meter.svg' %}"
                                                               height="50"
                                                               width="50"><br>
                                {% if not device %}
                                <small>(Счетчик № ------)<br><u>Дата след.поверки --.--.----</u></small>
                                {% endif %}
                                {%for dev in device %}
                                {% if "e" in dev.type %}
                                <small>({{dev.name}} № {{dev.number}})<br><u>Дата след.поверки
                                    {{dev.data_pov_next}}</u></small>
                                {% endif %}
                                {% endfor %}

                            </td>
                            <td></td>
                        </tr>
                        <tr>
                            <td><small>Последние показания <i><u>({{pokaz_dev.date}})</u></i>:
                                <b>{{pokaz_dev.e}}</b></small></td>
                        </tr>
                        <tr>
                            <td><small><span
                                    style="font-size: 12px;"><i>Вводите показания целым числом</i></span></small><br>
                                {{form_pokaz.e}}
                            </td>

                        </tr>
                    </table>
                    <div class=" my-2">
                        <input type="submit" class="btn btn-card" value="Передать">
                </form>
            </div>
        </div><!--div-->
    </div><!--col-->
    <div class="col-md-6 col-sm-12 my-1">
        <div class="container-cont">
            <div class="title_1">Заявки <a href="#" data-bs-toggle="modal" data-bs-target="#zayavkaModal"
                                           class="btn btn-sm btn-card">
                Добавить
            </a></div>
            <div class="form-error"></div>
            <table class="table-sm ">
                <thead>
                <tr>
                    <th><small>#</small></th>
                    <th><small>Дата</small></th>

                    <th><small>Статус</small></th>
                    <th><small>Действия</small></th>
                </tr>
                </thead>
                <tbody>
                {% for z in zayavki %}
                <tr>
                    <td><small>{{z.id}}</small></td>
                    <td><small>{{z.created|date:"d.m.y"}}</small></td>

                    <td><small>
                        {% if z.status == '2' %}
                        Ожидание
                        {% elif z.status == '1' %}
                        В работе
                        {% elif z.status == '0' %}
                        Выполнено
                        {% endif %}
                    </small></td>
                    <td><small>
                        <a class="btn btn-sm btn-card" href="{% url 'users:show_zayavka' z.id %}">Подробнее</a>
                    </small></td>
                </tr>
                {% endfor%}
                </tbody>
            </table>
        </div><!--cont-->

    </div><!--col-->
</div><!--row-->
<div class="row">
    <div class="col-md-6 col-sm-12 my-1 ">

        <div class="container-cont">
            <div class="title">Платежный документ</div>
            <form action="{%url 'users:receipt' %}" method="post">
                {% csrf_token%}
            <table class="table-sm">
                <tr>
                    <td>Месяц</td>
                    <td>Год</td>
                </tr>

                <tr>
                    <td>
                        <!--месяц-->
                        {{form_receipt.month}}
                    </td>
                    <td>
                        <!--Год-->
                        {{form_receipt.year}}

                    </td>
                    <td>
                        <button type="submit" class="btn btn-card ">Открыть</button>
                    </td>
                </tr>
            </table>
                </form>

        </div>

    </div>
</div><!--row-->
</div>
<!--MODAL WINDOW-->

<!--MODAL WINDOW END-->
<!-- zayavkaModal -->
<div class="modal fade" id="zayavkaModal" tabindex="-1" aria-labelledby="zayavkaModalLabel"
     aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="zayavkaModalLabel">Подача заявки</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal"
                        aria-label="Close"></button>
            </div>
            <form action="{% url 'users:zayavka_write_ajax'%}" method="POST" id="form_zayavka_write">
                {%csrf_token%}
            <div class="modal-body">
                <div class="alert alert-danger d-none error_zayavka" role="alert"></div>
                <div class="alert alert-success d-none ok_zayavka" role="alert"></div>
                <div class="row">
                    <div class="col">
                        <span style="color: gray;">{{form_zayavka.description.label}}</span>
                    </div><!--col-->
                </div><!--row-->
                <div class="row">
                    <div class="col">

                        {{form_zayavka.description}}
                    </div><!--col-->
                </div><!--row-->
                <div class="row">
                    <div class="col">
                        <span style="color: gray;">{{form_zayavka.phone.label}}</span>
                    </div><!--col-->
                </div><!--row-->
                <div class="row">
                    <div class="col">

                        {{form_zayavka.phone}}
                    </div><!--col-->
                </div><!--row-->

            </div><!--modal-body-->
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Отмена</button>
                <button type="submit" class="btn btn-card">Отправить</button>
                </form>
            </div>
        </div>
    </div>
</div>
<!-- zayavkaModal END-->
<!--CONTENT END-->

{% endblock content %}    

users/templates/users/profile.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <h3>Профиль пользователя</h3>
    <hr/>
    <div class="alert alert-danger d-none error" role="alert"></div>
<!--     <div class="alert alert-success d-none response" role="alert"></div>-->
    <div class="row">
        <div class="col-sm-12">
            <table class="table">
                <form method="POST">
                    {% csrf_token %}
                    <tr>
                        <td>ФИО</td>
                        <td>{{form.fio}}</td>
                        <td></td>
                    </tr>
                    <tr>
                        <td>Телефон</td>
                        <td>{{form.phone}}</td>
                        <td><a href="#" data-bs-toggle="modal" data-bs-target="#phoneModal" class="btn">
                            <svg
                                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007cba"
                                    class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path
                                        d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                            </svg>
                        </a></td>
                    </tr>
                    <tr>
                        <td>E-mail</td>
                        <td>{{form.email}}</td>
                        <td><a href="#" data-bs-toggle="modal" data-bs-target="#emailModal" class="btn">
                            <svg
                                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007cba"
                                    class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path
                                        d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                            </svg>
                        </a></td>

                    </tr>
                    <tr>
                        <td>Пароль</td>
                        <td>{{form.password}}</td>
                        <td><a href="#" data-bs-toggle="modal" data-bs-target="#passwordModal" class="btn">
                            <svg
                                    xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="#007cba"
                                    class="bi bi-pencil-fill" viewBox="0 0 16 16">
                                <path
                                        d="M12.854.146a.5.5 0 0 0-.707 0L10.5 1.793 14.207 5.5l1.647-1.646a.5.5 0 0 0 0-.708zm.646 6.061L9.793 2.5 3.293 9H3.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.207zm-7.468 7.468A.5.5 0 0 1 6 13.5V13h-.5a.5.5 0 0 1-.5-.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.5-.5V10h-.5a.5.5 0 0 1-.175-.032l-.179.178a.5.5 0 0 0-.11.168l-2 5a.5.5 0 0 0 .65.65l5-2a.5.5 0 0 0 .168-.11z"/>
                            </svg>
                        </a></td>
                    </tr>
                    <tr>
                        <td colspan="2">Способ получения платежных документов</td>

                    </tr>
                    <tr>
                        </form>
                <form action="{% url 'users:edit_rec_doc_ajax' %}" method="post" id="form_rec_doc">
                    {% csrf_token %}
                        {% if data_user.rec_doc == 1 %}
                    <td colspan="2"><input type="radio" name="rec_doc" value="0" id="paper0"> <label for="paper0">Бумажный</label> &nbsp;&nbsp;&nbsp;<input
                            type="radio" name="rec_doc" checked value="1" id="el0"> <label for="el0">E-mail</label>
                        </td>
                        {%else%}
                        <td colspan="2"><input type="radio" name="rec_doc" value="0" checked id="paper1"> <label for="paper1">Бумажный</label> &nbsp;&nbsp;&nbsp;<input
                                type="radio" name="rec_doc" value="1" id="el1"> <label for="el1">E-mail</label>
                        </td>
                        {%endif%}
                    </tr>
                    <tr>
                        <td colspan="2"><input type="submit" value="Сохранить" class="btn btn-card"></td>
                    </tr>
                    </form>
            </table>
        </div>
    </div>

</div><!--container-->

{% include 'users/modal.html' %}

{% endblock content %}    

users/templates/users/show_zayavka.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<!--CONTENT-->
<div class="container">
    <h3>Заявка # {{zayavka.id}} от {{zayavka.created|date:"d.m.y"}}</h3>
    <div class="row">
        <div class="col">
            <b>Описание:</b>
            {{zayavka.description}}
        </div><!--col-->
    </div><!--row-->
    <div class="row">
        <div class="col">
            <b>Статус:</b>
            {% if zayavka.status == '2' %}
                        Ожидание
                        {% elif zayavka.status == '1' %}
                        В работе
                        {% elif zayavka.status == '0' %}
                        Выполнено
                        {% endif %}
        </div><!--col-->
    </div><!--row-->
    <div class="row">
        <div class="col m-2 d-flex">
             <a class="btn btn-sm btn-card" href="{% url 'users:lk_user' %}">Назад</a>
            <form action="{% url 'users:delete_zayavka' zayavka.id %}" method="post">
        {% csrf_token %}
        <button class="btn btn-sm btn-danger">Удалить</button>
    </form>
        </div><!--col-->

    </div><!--row-->
</div>
<!--CONTENT END-->

{% endblock content %}

users/templates/users/verify_email.html
{% autoescape off %}

Здравствуйте, {{ user.get_username }}.
Пожалуйста, перейдите по ссылке, чтобы подтвердить регистрацию
{{ http }}{{ domain }}{% url 'users:verify_email' uidb64=uid token=token %}

{% endautoescape %}