bot/urls.py
from django.urls import path
from . import views
from django.views.decorators.csrf import csrf_exempt

app_name = "bot"

urlpatterns = [
    path('', csrf_exempt(views.index), name='index'),
    path('send_message', views.send_message, name='send_message'),

]

main/urls.py
from django.urls import path, re_path
from django.views.generic.base import TemplateView
from .views import *

urlpatterns = [
    # path("robots.txt",TemplateView.as_view(template_name="koleso/robots.txt", content_type="text/plain"),),
    path('', index, name='home'),
    path('contact/', contact, name='contact'),
    path('info/<slug:id_slug>/', show_info, name='show_info'),
    path('docs/<slug:id_slug>/', doc_list, name='doc_list'),
    path('doc/<slug:id_slug>/', show_doc, name='show_doc'),
    path('news/<slug:id_slug>/', show_news, name='show_news'),
    path('news_list/', news_list, name='news_list'),

]

tsn/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from main.views import pageNotFound

urlpatterns = [
    path('admin/', admin.site.urls),
    path('captcha/', include('captcha.urls')),
    path('', include('main.urls')),
    path('users/', include('users.urls', namespace="users")),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('bot/', include('bot.urls')),

]

handler404 = pageNotFound

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.views.generic import TemplateView

app_name = "users"

urlpatterns = [
    path('login/', views.login_user, name='login'),
    # path('login/', views.LoginUser.as_view(), name='login'),
    path('logout/', views.logout_user, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('lk/', views.lk_user, name='lk_user'),
    path('receipt/', views.receipt, name='receipt'),
    path('show_zayavka/<int:id>/', views.show_zayavka, name='show_zayavka'),
    path('delete_zayavka/<int:pk>/', views.deletezayavka, name='delete_zayavka'),
    # path('add_users/', views.add_user, name='add_users'),
    # path('add_pokazaniya/', views.add_pokazaniya, name='add_pokazaniya'),
    path('edit_phone_ajax/', views.EditPhoneAjax.as_view(), name='edit_phone_ajax'),
    path('edit_email_ajax/', views.EditEmailAjax.as_view(), name='edit_email_ajax'),
    path('edit_rec_doc_ajax/', views.EditRecDocAjax.as_view(), name='edit_rec_doc_ajax'),
    path('password_change_ajax/', views.ChangePasswordAjax.as_view(), name='password_change_ajax'),
    path('verify_email/<uidb64>/<token>/', views.EmailVerify.as_view(), name='verify_email'),
    path('invalid_verify/', TemplateView.as_view(template_name='users/invalid_verify.html'), name='invalid_verify'),
    path('pokazaniya_write_ajax/', views.PokazaniyaWriteAjax.as_view(), name='pokazaniya_write_ajax'),
    path('zayavka_write_ajax/', views.ZayavkaWriteAjax.as_view(), name='zayavka_write_ajax'),
]

main/forms.py
from multiprocessing import AuthenticationError
from django import forms
from .models import UserMessage, Zayavki
from captcha.fields import CaptchaField
from django.forms import ModelForm
from main.models import PokazaniyaUser
import datetime
from django.conf import settings


class AddMessageForm(forms.ModelForm):
    captcha = CaptchaField()

    class Meta:
        model = UserMessage
        fields = ['name', 'email', 'phone', 'message']
        widgets = {
            'name': forms.TextInput(
                attrs={'placeholder': 'Ваше имя', 'class': 'form-control form-value text-box single-line'}),
            'email': forms.EmailInput(
                attrs={'placeholder': 'E-mail', 'class': 'form-control form-value text-box single-line'}),
            'phone': forms.TextInput(
                attrs={'type': 'tel', 'placeholder': '+7 (999) 111 3333', 'id': 'online_phone', 'class': 'form-control',
                       'pattern': '[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}'}),
            'message': forms.Textarea(
                attrs={'placeholder': 'Сообщение', 'class': 'form-control form-value', 'cols': 20, 'rows': 4}),
        }


# форма передачи показаний
class PokazaniyaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        data = kwargs.pop('data', None)
        super(PokazaniyaForm, self).__init__(*args, **kwargs)
        if data:
            self.fields['kv'] = forms.IntegerField(
                widget=forms.NumberInput(attrs={'type': 'hidden', 'name': 'kv', 'value': data.kv})
            )

    cur_time = datetime.datetime.now()

    hv = forms.CharField(label='Холодная вода',
                         widget=forms.NumberInput(
                             attrs={'placeholder': 'Холодная вода', 'min': 0})
                         )
    gv = forms.CharField(label='Горячая вода',
                         widget=forms.NumberInput(
                             attrs={'placeholder': 'Горячая вода', 'min': 0})
                         )
    e = forms.CharField(label='Электричество',
                        widget=forms.NumberInput(
                            attrs={'placeholder': 'Электричество', 'required': 'False', 'min': 0})
                        )

    class Meta:
        model = PokazaniyaUser
        fields = ['kv', 'hv', 'gv', 'e']


# Форма передачи заявки
class ZayavkaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        data = kwargs.pop('data', None)
        super(ZayavkaForm, self).__init__(*args, **kwargs)
        if data:
            self.fields['ls'] = forms.IntegerField(
                widget=forms.NumberInput(attrs={'type': 'hidden', 'name': 'ls', 'value': data.ls})
            )

    description = forms.CharField(label="Описание",
                                  widget=forms.Textarea(
                                      attrs={"class": "form-control form-value", "placeholder": "Опешите проблему",
                                             'cols': 20, 'rows': 4}
                                  ))
    phone = forms.CharField(label="Телефон",
                            widget=forms.TextInput(
                                attrs={'type': 'tel', 'placeholder': '+7 (999) 111 3333', 'id': 'online_phone',
                                       'class': 'form-control',
                                       'pattern': '[+]{1}7 [(]{1}[0-9]{3}[)]{1} [0-9]{3} [0-9]{4}'}
                            ))

    class Meta:
        model = Zayavki
        fields = ['description', 'phone']


class MeterImportForm(forms.Form):
    csv_file = forms.FileField(label="CSV Файл с номерами счетчикков")

main/views.py
from django.shortcuts import get_object_or_404, redirect, render
from .models import *
from .forms import *
from django.core.mail import send_mail
from django.conf import settings
from django.core.paginator import Paginator
from .utils import paginate

# return HttpResponse(f"Отображение статьи с id = {post_id}")
col = 6  # для пагинации


#########################################################################################
def index(request):
    news = News.objects.all().order_by('-id')[:3]
    context = {
        'title': 'Главная',
        'news': news,
    }
    return render(request, 'main/index.html', context)


#########################################################################################
def contact(request):
    if request.method == 'POST':
        form = AddMessageForm(request.POST)
        if form.is_valid():
            x = request.POST.dict()
            mess = "Новое сообщение от " + x.get('name') + "; e-mail: " + x.get('email') + "; Тел: " + x.get(
                'phone') + "; Сообщение: " + x.get('message')
            form.save()
            send_mail('Уведомление с сайта ТСН', mess, settings.EMAIL_HOST_USER,
                      [settings.EMAIL_FROM_ADMIN, settings.EMAIL_FROM_CLIENT], fail_silently=False, )
            return redirect('home')
    else:
        form = AddMessageForm()
    context = {
        'title': 'Контакты',
        'form': form,
    }
    return render(request, 'main/contact.html', context)


#########################################################################################
def show_info(request, id_slug):
    info = get_object_or_404(Info, slug=id_slug)
    context = {
        'info': info,
    }
    return render(request, 'main/info.html', context)


#########################################################################################
def doc_list(request, id_slug):
    title = KatDoc.objects.get(slug=id_slug)
    docs_list = Doc.objects.all().filter(kat_id__slug=id_slug)
    # Постраничная разбивка с col постами на страницу
    custom_range, docs = paginate(request, docs_list, 6)

    context = {
        'title': title.name,
        'custom_range': custom_range,
        'docs': docs,
    }
    return render(request, 'main/doc_list.html', context)


#########################################################################################
def show_doc(request, id_slug):
    document = get_object_or_404(Doc, slug=id_slug)
    count = document.views + 1
    document.views = count
    document.save(update_fields=['views'])
    context = {
        'document': document,
        'count': count
    }
    return render(request, 'main/show_doc.html', context)


#########################################################################################
def show_news(request, id_slug):
    document = get_object_or_404(News, slug=id_slug)
    count = document.views + 1
    document.views = count
    document.save(update_fields=['views'])
    context = {
        'document': document,
        'count': count
    }
    return render(request, 'main/show_news.html', context)


#########################################################################################
def news_list(request):
    news_list = News.objects.all().order_by('-id')
    # Постраничная разбивка с col постами на страницу
    custom_range, nws = paginate(request, news_list, 6)

    context = {
        'news_list': nws,
        'custom_range': custom_range,
    }
    return render(request, 'main/news_list.html', context)


#########################################################################################
def pageNotFound(request, exception):
    context = {
        'title': 'Страница не найдена',
    }
    return render(request, 'main/page_not_found.html', context)
#########################################################################################

main/templates/main/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{title}}</title>
    <link rel="shortcut icon" href="{% static 'main/img/favicon.ico' %}">
    <link rel="stylesheet" href="{% static 'main/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'main/css/style.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css">
    <!-- <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.1/font/bootstrap-icons.css"> -->

</head>

<body>

<div class="wrapper">
    <header class="header">
        <!--NAVIGATION -->
        <nav class="navbar navbar-expand-lg">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'home' %}">ТСН «ЗВЕЗДНЫЙ-7»</a>
                <button class="navbar-toggler " type="button" data-bs-toggle="collapse"
                        data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Переключатель навигации">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <!---->
                        <li class="nav-item">
                            <a class="nav-link " aria-current="page" href="{% url 'news_list' %}">Новости</a>
                        </li>
                        <!---->
                        {%if infos %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Информация о ТСН
                            </a>
                            <ul class="dropdown-menu">
                                {% for info in infos %}
                                <li><a class="dropdown-item" href="{{ info.get_absolute_url }}">{{info.title}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {%endif%}
                        <!---->
                        {%if kat_doc%}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">
                                Документы
                            </a>
                            <ul class="dropdown-menu">
                                {% for kat in kat_doc%}
                                <li><a class="dropdown-item" href="{{ kat.get_absolute_url }}">{{kat.name}}</a></li>
                                {% endfor %}
                            </ul>
                        </li>
                        {%endif%}
                        <!---->
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'contact' %}">Контакты</a>
                        </li>
                        <!---->

                    </ul>
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                               aria-expanded="false">Л/Сч.</i>&nbsp;{{user.username}}</a>
                            <ul class="dropdown-menu">
                                {% if request.user.is_superuser %}
                                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админ панель</a></li>
                                {% endif %}
                                <li><a class="dropdown-item" href="{% url 'users:lk_user' %}">Личный кабинет</a></li>
                                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
                                <li>
                                    <form action="{% url 'users:logout' %}" method="POST">
                                        {% csrf_token %}
                                        <button class="dropdown-item">Выход</button>
                                    </form>
                                </li>
                                <!--<li><a class="dropdown-item" href="{% url 'users:logout' %}">Выход</a></li>-->

                                {% else %}
                                <li><a class="nav-link" href="{% url 'users:login' %}"><i
                                        class="bi bi-box-arrow-right"></i> Личный кабинет</a></li>
                                {% endif %}
                            </ul>
                </div>
            </div>
        </nav>
        <!--NAVIGATION END-->
    </header>
    <main class="main">


        <!-------------------------------------------------------->
        {%block content %}
        {% endblock %}
        <!-------------------------------------------------------->
        {% block footer %}
        {% endblock %}

    </main>
    <footer class="footer bg-white">

        <div class="container">
            <hr class="space m"/>

            <div class="row copy-row">
                <div class="col-md-12 text-center">
                    &copy; {{year}} ТСН &quot;ЗВЕЗДНЫЙ-7&quot;
                    <span class="text-right"> <br><a href="mailto:sar-bc@mail.ru" target="_blank">Разработка сайта -
                    sar-bc@mail.ru</a></span>
                </div>
            </div>
        </div><!--container-->
    </footer>
</div>
<script src="{% static 'main/js/bootstrap.bundle.min.js' %}"></script>
<script src="{% static 'main/js/jquery.min.js' %}"></script>
<script src="{% static 'main/js/main.js' %}"></script>
<script src="{% static 'users/js/form.js' %}"></script>
<!-- Yandex.Metrika counter -->
<script type="text/javascript">
    (function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
    m[i].l=1*new Date();
    for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
    k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
    (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");

    ym(97983501, "init", {
         clickmap:true,
         trackLinks:true,
         accurateTrackBounce:true
    });
</script>
<noscript>
    <div><img src="https://mc.yandex.ru/watch/97983501" style="position:absolute; left:-9999px;" alt=""/></div>
</noscript>
<!-- /Yandex.Metrika counter -->
</body>

</html>    

main/templates/main/contact.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6 py-3">
            <div class="card">
                <h5 class="card-header">Обратная связь</h5>
                <form action="{% url 'contact' %}" class="form-box"  method="post">
                    {% csrf_token %}
                    <div class="form-error">{{ form.non_field_errors }}</div>
                <div class="card-body">
                    <div class="form-error"></div>
                    <p>{{ form.name }}</p>
                    <p>{{ form.email }}</p>
                    <p>{{ form.phone }}</p>
                    <p>{{form.message}}</p>
                    <p>{{form.captcha}}</p>
                    <p><button type="submit" class="btn btn-card">Отправить сообщение</button></p>
                </form>
                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/doc_list.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
<h1>{{title}}</h1>
<hr class="space m" />
    <div class="row  py-1 px-2 ">
    {% for d in docs %} 
<!--CARD-->
<div class="col-md-4 col-sm-12 my-2">
    <div class="card h-100">
        <div class="card-header">{{d.title}}</div>
        <div class="card-body">
        {% comment %} <h5 class="card-title">{{d.title}}</h5> {% endcomment %}
        <p style="text-align: left"><i class="bi bi-calendar-week"></i> <span class="">{{d.publish|date:"d-m-Y" }}</span></p>
        <p class="card-text">{{d.content|safe|truncatewords:15}}</p>
        
        </div>
        <div class="card-footer text-body-secondary text-center">
            <a href="{{ d.get_absolute_url }}" class="btn btn-card">Подробней</a>
        </div>
    </div>
</div><!--col-->
<!--CARD END-->
{% endfor %}

{% include "main/pagination.html" with queryset=docs %}

    
    </div><!--row-->
</div><!--container-->
{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/footer.html
<!--FOOTER CARD-->
<div class="container">
    <hr/>
    <div class="row">
                    
                    {% for card in cards%}
<!--CARD-->
<div class="col-md-4 col-sm-12 py-1">
    <div class="container  box box-fon h-100">
    <div class="row">
        <div class="col">
            <h5 class="card-title text-center text-m"><u>{{card.title}}</u></h5>
        </div>
    </div>
    <div class="row">
        <div class="col">
            {% autoescape off %}
            {{card.description}}
            {% endautoescape %}
        </div>
    </div>
    </div>
</div>
<!--CARD END-->
                    {% endfor %}
            
    </div><!--row-->
</div><!--container-->
<!--FOOTER CARD END-->

main/templates/main/index.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
    <!-- НОВОСТИ 3 ШТ -->
                <div class="container">
                    <h2>Новости</h2>
                    <hr>
                    <div class="row">
                        
                        {% for n in news%}
<!-- НОВОСТЬ START -->
<div Class="col-md-4 col-sm-12  py-1">
    <div class="container box box-fon h-100"> 
        <div class="row">
            {% if n.img %}
            <div class="col img-box150" style="background-image: url({{n.img.url}});">
                {%else%}
                <div class="col img-box150" style="background-image: url({% static 'main/img/dom.png' %});">
                {%endif%}
                <span class="box-data ">{{n.publish|date:"d-m-Y" }}</span> 
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="box-content">
                    <h4 class="text-m text-center">{{n.title}}</h4>
                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col ">
                <div class="box-content">
                    {{n.body|safe|truncatewords:15}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-center ">
                <a class="btn btn-sm btn-card" href="{{ n.get_absolute_url }}">Подробнее</a>
            </div>
            <hr class="space m" />
        </div>
    </div>
</div>   
<!--НОВОСТЬ END-->
                        {% endfor %}
                    </div> <!--row-->
                </div><!--container-->
                <!-- НОВОСТИ 3 ШТ END-->
{% endblock %}

{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/info.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row py-1 px-2">
        <div class="col-sm-12">
            <div class="card">
                <h5 class="card-header">{{info.title}}</h5>
                <div class="card-body">
                <p class="card-text">
                    {{info.content|safe}}
                </p>
                {% if info.file %}
                <hr class="space m" />
                <p><iframe width="100%" height="800px" src="{{info.file.url}}" type="application/pdf"></iframe></p>
                {% endif %}
                </div>
            </div>
        </div>
    </div>   
</div>
{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/news_list.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <h3>Новости</h3>
    <hr/>
        <div class="row">
        {% for n in news_list %} 
<!-- НОВОСТЬ START -->
<div Class="col-md-4 col-sm-12 py-1">
    <div class="container box box-fon h-100"> 
        <div class="row">
            {% if n.img %}
            <div class="col img-box150" style="background-image: url({{n.img.url}});">
                {%else%}
                <div class="col img-box150" style="background-image: url({% static 'main/img/dom.png' %});">
                {%endif%}
                <span class="box-data ">{{n.publish|date:"d-m-Y" }}</span> 
            </div>
        </div>
        <div class="row">
            <div class="col">
                <div class="box-content">
                    <h4 class="text-m text-center">{{n.title}}</h4>
                </div>
            </div>
        </div>
        <div class="row ">
            <div class="col ">
                <div class="box-content">
                    {{n.body|safe|truncatewords:15}}
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col text-center ">
                <a class="btn btn-sm btn-card" href="{{ n.get_absolute_url }}">Подробнее</a>
            </div>
            <hr class="space m" />
        </div>
    </div>
</div>   
<!--НОВОСТЬ END-->

    {% endfor %}

    {% include "main/pagination.html" with queryset=news_list %}


{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/page_not_found.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<h1 style="text-align: center;">Страница не найдена</h1>
{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/pagination.html
{% if queryset.has_other_pages %}
<!--больше одной страницы-->
<nav aria-label="Пример навигации по страницам">
    <ul class="pagination justify-content-center">
        {% if queryset.has_previous %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page.previous_page_number }}"
               data-page="{{ page.previous_page_number }}">
                &lt;</a>
        </li>
        {%endif%}

        {% for page in custom_range %}

        {% if page == queryset.number %}
        <li class="page-item active"><span class="page-link">{{ page }}</span></li>
        {% else %}
        <li class="page-item">
            <a class="page-link" href="?page={{ page }}" data-page="{{ page }}">{{ page }}</a>
        </li>
        {% endif %}

        {% endfor %}


        {% if queryset.has_next %}
        <li class="page-item">
            <a class="page-link" href="?page={{ queryset.next_page_number }}" data-page="{{queryset.next_page_number}}">&gt;</a>
        </li>

        {%endif%}
    </ul>
</nav>
{% endif %}

main/templates/main/show_doc.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row py-1 px-2">
        <div class="col-sm-12">
            <div class="card">
                <h5 class="card-header">{{document.title}}</h5>
                
                <div class="card-body">
                    <p style="text-align: left"><span style="color:gray;"><i class="bi bi-calendar-week"></i>
                        Создано: {{document.publish|date:"d-m-Y" }}<br><i class="bi bi-eye"></i> Просмотров:
                        {{count}}</span></p>
                    {{document.content|safe}}
                
                {% if document.file %}
                <hr class="space m" />
                <iframe width="100%" height="800px" src="{{document.file.url}}" type="application/pdf"></iframe>
                {% endif %}
                </div>
            </div>
        </div>
    </div>   
</div>   
{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}

main/templates/main/show_news.html
{% extends 'main/base.html' %}
{% load static %}


{% block content %}
<div class="container">
    <div class="row py-1 px-2">
        <div class="col-sm-12">
            <div class="card">
                <h5 class="card-header">{{document.title}}</h5>

                <div class="card-body">

<!--                    <p style="text-align: left"><span style="color:gray;"><i class="bi bi-calendar-week"></i> Создано: {{document.publish|date:"d-m-Y" }}</span>-->
<!--                    </p>-->
                    {% if document.img %}
                    <img align="left" src="{{document.img.url}}" class="card-img-top img_show  img_w" alt="...">
                    {%else%}
                    <img align="left" src="{% static 'main/img/dom.png' %}" class="card-img-top img_show  img_w"
                         alt="...">
                    {%endif%}
                    <p style="text-align: left"><span style="color:gray;"><i class="bi bi-calendar-week"></i>
                        Создано: {{document.publish|date:"d-m-Y" }} <i class="bi bi-eye"></i> Просмотров: {{count}}</span>
                    </p>
                    {{document.body|safe}}

                    {% if document.file %}
                    <hr class="space m"/>
                    <iframe width="100%" height="800px" src="{{document.file.url}}" type="application/pdf"></iframe>
                    {% endif %}

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}


{% block footer %}
{% include "main/footer.html" with page=card %}
{% endblock %}